from enum import Enum

class CounterType(Enum):
    PACKETS_UP = 'PACKETS_UP'
    PACKETS_DOWN = 'PACKETS_DOWN'
    PACKETS_LOST = 'PACKETS_LOST'
    JOIN_REQUESTS = 'JOIN_REQUESTS'
    FAILED_JOIN_REQUESTS = 'FAILED_JOIN_REQUESTS'
    RETRANSMISSIONS = 'RETRANSMISSIONS'